### ISSUE TITLE
Start a new version of the paper

### ISSUE THREAD

**Issue by aimalz** [aimalz/chippr#41]
I'll be making a pared down revision of [the paper](https://github.com/aimalz/prob-z/tree/master/nz/paper).  

- [x] Consider a new title.
- [x] Revise the abstract.
- [x] Streamline the introduction.

**Comment by aimalz** [comment]
@drphilmarshall if it sounds reasonable to you, I'll develop the outline in the existing `issue/41/reboot_paper` branch and close #41 when the outline is merged into the `master` branch.

**Comment by drphilmarshall** [comment]
Seems like a sensible pre-set name! Go for it.

**Comment by aimalz** [comment]
Now that there's a legit outline, I'm going to consider the "start" phase of the paper to be complete.  The goal is now to keep the paper up-to-date with other changes until I'm ready to wrap it up.
