### ISSUE TITLE
Epic: refactoring

### ISSUE THREAD

**Issue by aimalz** [aimalz/chippr#66]
This issue is for collecting programming issues that are driving me nuts but aren't actually holding back completion of the paper.

- [ ] Establish consistent keyword/variable names (#15)
- [ ] Improve user interface with error checks (#26)
- [ ] Improve file formats (#51)
- [ ] Diagnostic printouts to file (#52)
- [ ] Eliminate the abundant magic numbers and give more control to the user via an improved config file interface.
- [ ] Use `qp` (or `pomegranate`) for probability distributions to replace `discrete.py`,  `gauss.py`, and `gmix.py`
