### ISSUE TITLE
Epic: paper 0

### ISSUE THREAD

**Issue by aimalz** [aimalz/chippr#72]
I'm going to collect issues here now that this is progressing again.

- [ ] Gather relevant references. (#65)
- [ ] Document demo for publication. (#54)
- [ ] Finish validating/interpreting propagation to cosmology (#49)
- [ ] Scale up to more galaxies. (#60)
- [ ] Make a forecast for Euclid. (#69)
- [ ] Polish the sloppy plots.
- [ ] Write a brief version of the math into an appendix.
- [ ] Write a brief version of the mock data emulation procedure into an appendix.
- [ ] Run sampler as well as optimizer.

**Comment by aimalz** [comment]
So, #78 merged the branch for this issue into the master branch, but the issue isn't ready to close.  It looks like paper 0 got so overgrown that it was really papers 0, 1, and 2 combined.  So, the next step is to split up what's currently in the master branch into three papers simultaneously.  I think it might be best to close this issue and start a new one for that distinct task.
